services:
  db:
    image: mysql:latest
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=jpa
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
volumes:
  db_data: