version: '3'

services:
  db:
    image: mysql
    volumes:
      - jpa_db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=jpa
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
volumes:
  jpa_db: