spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/jpa?createDatabaseIfNotExist=true&connectionTimeZone=UTC
    username: root
    password: root
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create